<a href="https://colab.research.google.com/github/mowgli28/DS-Unit-1-Sprint-4-Statistical-Tests-and-Experiments/blob/master/Hypothesis_testing_sprint_challenge_complete.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "DS Unit 1 Sprint Challenge 4.ipynb",
      "version": "0.3.2",
      "provenance": [],
      "collapsed_sections": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    }
  },
  "cells": [
    {
      "metadata": {
        "id": "NooAiTdnafkz",
        "colab_type": "text"
      },
      "cell_type": "markdown",
      "source": [
        "# Data Science Unit 1 Sprint Challenge 4\n",
        "\n",
        "## Exploring Data, Testing Hypotheses\n",
        "\n",
        "In this sprint challenge you will look at a dataset of people being approved or rejected for credit.\n",
        "\n",
        "https://archive.ics.uci.edu/ml/datasets/Credit+Approval\n",
        "\n",
        "Data Set Information: This file concerns credit card applications. All attribute names and values have been changed to meaningless symbols to protect confidentiality of the data. This dataset is interesting because there is a good mix of attributes -- continuous, nominal with small numbers of values, and nominal with larger numbers of values. There are also a few missing values.\n",
        "\n",
        "Attribute Information:\n",
        "- A1: b, a.\n",
        "- A2: continuous.\n",
        "- A3: continuous.\n",
        "- A4: u, y, l, t.\n",
        "- A5: g, p, gg.\n",
        "- A6: c, d, cc, i, j, k, m, r, q, w, x, e, aa, ff.\n",
        "- A7: v, h, bb, j, n, z, dd, ff, o.\n",
        "- A8: continuous.\n",
        "- A9: t, f.\n",
        "- A10: t, f.\n",
        "- A11: continuous.\n",
        "- A12: t, f.\n",
        "- A13: g, p, s.\n",
        "- A14: continuous.\n",
        "- A15: continuous.\n",
        "- A16: +,- (class attribute)\n",
        "\n",
        "Yes, most of that doesn't mean anything. A16 (the class attribute) is the most interesting, as it separates the 307 approved cases from the 383 rejected cases. The remaining variables have been obfuscated for privacy - a challenge you may have to deal with in your data science career.\n",
        "\n",
        "Sprint challenges are evaluated based on satisfactory completion of each part. It is suggested you work through it in order, getting each aspect reasonably working, before trying to deeply explore, iterate, or refine any given step. Once you get to the end, if you want to go back and improve things, go for it!"
      ]
    },
    {
      "metadata": {
        "id": "5wch6ksCbJtZ",
        "colab_type": "text"
      },
      "cell_type": "markdown",
      "source": [
        "## Part 1 - Load and validate the data\n",
        "\n",
        "- Load the data as a `pandas` data frame.\n",
        "- Validate that it has the appropriate number of observations (you can check the raw file, and also read the dataset description from UCI).\n",
        "- UCI says there should be missing data - check, and if necessary change the data so pandas recognizes it as na\n",
        "- Make sure that the loaded features are of the types described above (continuous values should be treated as float), and correct as necessary\n",
        "\n",
        "This is review, but skills that you'll use at the start of any data exploration. Further, you may have to do some investigation to figure out which file to load from - that is part of the puzzle."
      ]
    },
    {
      "metadata": {
        "id": "Q79xDLckzibS",
        "colab_type": "code",
        "colab": {}
      },
      "cell_type": "code",
      "source": [
        "# TODO"
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "metadata": {
        "id": "G7rLytbrO38L",
        "colab_type": "text"
      },
      "cell_type": "markdown",
      "source": [
        "## Part 2 - Exploring data, Testing hypotheses\n",
        "\n",
        "The only thing we really know about this data is that A16 is the class label. Besides that, we have 6 continuous (float) features and 9 categorical features.\n",
        "\n",
        "Explore the data: you can use whatever approach (tables, utility functions, visualizations) to get an impression of the distributions and relationships of the variables. In general, your goal is to understand how the features are different when grouped by the two class labels (`+` and `-`).\n",
        "\n",
        "For the 6 continuous features, how are they different when split between the two class labels? Choose two features to run t-tests (again split by class label) - specifically, select one feature that is *extremely* different between the classes, and another feature that is notably less different (though perhaps still \"statistically significantly\" different). You may have to explore more than two features to do this.\n",
        "\n",
        "For the categorical features, explore by creating \"cross tabs\" between them and the class label, and apply the Chi-squared test to them. There are 9 categorical features - as with the t-test, try to find one where the Chi-squared test returns an extreme result (rejecting the null that the data are independent), and one where it is less extreme.\n",
        "\n",
        "**NOTE** - \"less extreme\" just means smaller test statistic/larger p-value. Even the least extreme differences may be strongly statistically significant.\n",
        "\n",
        "Your *main* goal is the hypothesis tests, so don't spend too much time on the exploration/visualization piece. That is just a means to an end. This is challenging, so manage your time and aim for a baseline of at least running two t-tests and two Chi-squared tests before polishing. And don't forget to answer the questions in part 3, even if your results in this part aren't what you want them to be."
      ]
    },
    {
      "metadata": {
        "id": "_nqcgc0yzm68",
        "colab_type": "code",
        "colab": {}
      },
      "cell_type": "code",
      "source": [
        "# TODO"
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "metadata": {
        "id": "ZM8JckA2bgnp",
        "colab_type": "text"
      },
      "cell_type": "markdown",
      "source": [
        "## Part 3 - Analysis and Interpretation\n",
        "\n",
        "Now that you've looked at the data, answer the following questions:\n",
        "\n",
        "- Interpret and explain the two t-tests you ran - what do they tell you about the relationships between the continuous features you selected and the class labels?\n",
        "- Interpret and explain the two Chi-squared tests you ran - what do they tell you about the relationships between the categorical features you selected and the class labels?\n",
        "- What was the most challenging part of this sprint challenge?\n",
        "\n",
        "Answer with text, but feel free to intersperse example code/results or refer to it from earlier."
      ]
    },
    {
      "metadata": {
        "id": "LIozLDNG2Uhu",
        "colab_type": "text"
      },
      "cell_type": "markdown",
      "source": [
        "*Your words here!*"
      ]
    }
  ]
}

In [0]:
import pandas as pd
import numpy as np
from scipy.stats import chisquare

# https://archive.ics.uci.edu/ml/datasets/Credit+Approval

df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/credit-screening/crx.data', header = None)

In [5]:
df.head()

  0      1      2  3  4  5  6     7  8  9   10 11 12     13   14 15
0  b  30.83  0.000  u  g  w  v  1.25  t  t   1  f  g  00202    0  +
1  a  58.67  4.460  u  g  q  h  3.04  t  t   6  f  g  00043  560  +
2  a  24.50  0.500  u  g  q  h  1.50  t  f   0  f  g  00280  824  +
3  b  27.83  1.540  u  g  w  v  3.75  t  t   5  t  g  00100    3  +
4  b  20.17  5.625  u  g  w  v  1.71  t  f   0  f  s  00120    0  +

In [67]:
df.describe()

               2           7          10             14
count  690.000000  690.000000  690.00000     690.000000
mean     4.758725    2.223406    2.40000    1017.385507
std      4.978163    3.346513    4.86294    5210.102598
min      0.000000    0.000000    0.00000       0.000000
25%      1.000000    0.165000    0.00000       0.000000
50%      2.750000    1.000000    0.00000       5.000000
75%      7.207500    2.625000    3.00000     395.500000
max     28.000000   28.500000   67.00000  100000.000000

In [26]:
df.replace({'?': 'na'})

     0      1       2  3  4   5   6       7  8  9   10 11 12     13     14 15
0     b  30.83   0.000  u  g   w   v   1.250  t  t   1  f  g  00202      0  +
1     a  58.67   4.460  u  g   q   h   3.040  t  t   6  f  g  00043    560  +
2     a  24.50   0.500  u  g   q   h   1.500  t  f   0  f  g  00280    824  +
3     b  27.83   1.540  u  g   w   v   3.750  t  t   5  t  g  00100      3  +
4     b  20.17   5.625  u  g   w   v   1.710  t  f   0  f  s  00120      0  +
5     b  32.08   4.000  u  g   m   v   2.500  t  f   0  t  g  00360      0  +
6     b  33.17   1.040  u  g   r   h   6.500  t  f   0  t  g  00164  31285  +
7     a  22.92  11.585  u  g  cc   v   0.040  t  f   0  f  g  00080   1349  +
8     b  54.42   0.500  y  p   k   h   3.960  t  f   0  f  g  00180    314  +
9     b  42.50   4.915  y  p   w   v   3.165  t  f   0  t  g  00052   1442  +
10    b  22.08   0.830  u  g   c   h   2.165  f  f   0  t  g  00128      0  +
11    b  29.92   1.835  u  g   c   h   4.335  t  f   0  f  g  00260    200  +
12    a  38.25   6.000  u  g   k   v   1.000  t  f   0  t  g  00000      0  +
13    b  48.08   6.040  u  g   k   v   0.040  f  f   0  f  g  00000   2690  +
14    a  45.83  10.500  u  g   q   v   5.000  t  t   7  t  g  00000      0  +
15    b  36.67   4.415  y  p   k   v   0.250  t  t  10  t  g  00320      0  +
16    b  28.25   0.875  u  g   m   v   0.960  t  t   3  t  g  00396      0  +
17    a  23.25   5.875  u  g   q   v   3.170  t  t  10  f  g  00120    245  +
18    b  21.83   0.250  u  g   d   h   0.665  t  f   0  t  g  00000      0  +
19    a  19.17   8.585  u  g  cc   h   0.750  t  t   7  f  g  00096      0  +
20    b  25.00  11.250  u  g   c   v   2.500  t  t  17  f  g  00200   1208  +
21    b  23.25   1.000  u  g   c   v   0.835  t  f   0  f  s  00300      0  +
22    a  47.75   8.000  u  g   c   v   7.875  t  t   6  t  g  00000   1260  +
23    a  27.42  14.500  u  g   x   h   3.085  t  t   1  f  g  00120     11  +
24    a  41.17   6.500  u  g   q   v   0.500  t  t   3  t  g  00145      0  +
25    a  15.83   0.585  u  g   c   h   1.500  t  t   2  f  g  00100      0  +
26    a  47.00  13.000  u  g   i  bb   5.165  t  t   9  t  g  00000      0  +
27    b  56.58  18.500  u  g   d  bb  15.000  t  t  17  t  g  00000      0  +
28    b  57.42   8.500  u  g   e   h   7.000  t  t   3  f  g  00000      0  +
29    b  42.08   1.040  u  g   w   v   5.000  t  t   6  t  g  00500  10000  +
..   ..    ...     ... .. ..  ..  ..     ... .. ..  .. .. ..    ...    ... ..
660   b  22.25   9.000  u  g  aa   v   0.085  f  f   0  f  g  00000      0  -
661   b  29.83   3.500  u  g   c   v   0.165  f  f   0  f  g  00216      0  -
662   a  23.50   1.500  u  g   w   v   0.875  f  f   0  t  g  00160      0  -
663   b  32.08   4.000  y  p  cc   v   1.500  f  f   0  t  g  00120      0  -
664   b  31.08   1.500  y  p   w   v   0.040  f  f   0  f  s  00160      0  -
665   b  31.83   0.040  y  p   m   v   0.040  f  f   0  f  g  00000      0  -
666   a  21.75  11.750  u  g   c   v   0.250  f  f   0  t  g  00180      0  -
667   a  17.92   0.540  u  g   c   v   1.750  f  t   1  t  g  00080      5  -
668   b  30.33   0.500  u  g   d   h   0.085  f  f   0  t  s  00252      0  -
669   b  51.83   2.040  y  p  ff  ff   1.500  f  f   0  f  g  00120      1  -
670   b  47.17   5.835  u  g   w   v   5.500  f  f   0  f  g  00465    150  -
671   b  25.83  12.835  u  g  cc   v   0.500  f  f   0  f  g  00000      2  -
672   a  50.25   0.835  u  g  aa   v   0.500  f  f   0  t  g  00240    117  -
673  na  29.50   2.000  y  p   e   h   2.000  f  f   0  f  g  00256     17  -
674   a  37.33   2.500  u  g   i   h   0.210  f  f   0  f  g  00260    246  -
675   a  41.58   1.040  u  g  aa   v   0.665  f  f   0  f  g  00240    237  -
676   a  30.58  10.665  u  g   q   h   0.085  f  t  12  t  g  00129      3  -
677   b  19.42   7.250  u  g   m   v   0.040  f  t   1  f  g  00100      1  -
678   a  17.92  10.210  u  g  ff  ff   0.000  f  f   0  f  g  00000     50  -
679   a  20.08   1.250  u  g   c   v   0.000  f  f   0  f  g  00000      0  -
680   b  19.50   0.290  u  g   k   v   0.290  f  f   0  f  g  00280    364  -
681   b  27.83   1.000  y  p   d   h   3.000  f  f   0  f  g  00176    537  -
682   b  17.08   3.290  u  g   i   v   0.335  f  f   0  t  g  00140      2  -
683   b  36.42   0.750  y  p   d   v   0.585  f  f   0  f  g  00240      3  -
684   b  40.58   3.290  u  g   m   v   3.500  f  f   0  t  s  00400      0  -
685   b  21.08  10.085  y  p   e   h   1.250  f  f   0  f  g  00260      0  -
686   a  22.67   0.750  u  g   c   v   2.000  f  t   2  t  g  00200    394  -
687   a  25.25  13.500  y  p  ff  ff   2.000  f  t   1  t  g  00200      1  -
688   b  17.92   0.205  u  g  aa   v   0.040  f  f   0  f  g  00280    750  -
689   b  35.00   3.375  u  g   c   h   8.290  f  f   0  t  g  00000      0  -

[690 rows x 16 columns]

In [0]:
import matplotlib.pyplot as plt

In [0]:
from scipy.stats import chisquare
import numpy as np 
a = np.array(df[10])
b = np.array(df[2])

In [58]:
print(chisquare(a, axis=None))

Power_divergenceResult(statistic=6789.0, pvalue=0.0)

In [59]:
print(chisquare(b, axis=None))

Power_divergenceResult(statistic=3588.1196387108957, pvalue=0.0)

In [38]:
from scipy import stats
stats.ttest_1samp(df[2], 0.5)

Ttest_1sampResult(statistic=22.47165047814236, pvalue=2.5723897481285845e-84)

In [68]:
stats.ttest_1samp(df[10], 0.5)

Ttest_1sampResult(statistic=13.527561959767695, pvalue=3.7917313931450475e-37)

In [43]:
|stats.ttest_ind(df[2], df[10])

Ttest_indResult(statistic=8.903140583809282, pvalue=1.6735067464491046e-18)

In [0]:
# I attempted to run ttests on all of the columns and found that the only 
# columns from the dataframe that would allow for the successful ttest
# providing me with stats and a p-value were columns 2, 7, 10, & 14. When
# I ran my chisquare tests on columns 2 & 10 I found a pvalue of 0
# with very high statistics (6789, & 3588), which would in turn mean there is a dependence.
# When running my ttests on these 2 columns I returned very low p-values 
# which also means we reject the null hypothesis that these are independent values.
# The hardest part of the challeng I would say would be for me, trying to figure
# out why only 4 of the 6 columns were able to function with my ttest and chisquare test.