<a href="https://colab.research.google.com/github/RedZeptic/DS-Unit-1-Sprint-3-Statistical-Tests-and-Experiments/blob/master/module2-sampling-confidence-intervals-and-hypothesis-testing/Thomas_Mineo_LS_DS_132_Sampling_Confidence_Intervals_and_Hypothesis_Testing_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment - Build a confidence interval

A confidence interval refers to a neighborhood around some point estimate, the size of which is determined by the desired p-value. For instance, we might say that 52% of Americans prefer tacos to burritos, with a 95% confidence interval of +/- 5%.

52% (0.52) is the point estimate, and +/- 5% (the interval $[0.47, 0.57]$) is the confidence interval. "95% confidence" means a p-value $\leq 1 - 0.95 = 0.05$.

In this case, the confidence interval includes $0.5$ - which is the natural null hypothesis (that half of Americans prefer tacos and half burritos, thus there is no clear favorite). So in this case, we could use the confidence interval to report that we've failed to reject the null hypothesis.

But providing the full analysis with a confidence interval, including a graphical representation of it, can be a helpful and powerful way to tell your story. Done well, it is also more intuitive to a layperson than simply saying "fail to reject the null hypothesis" - it shows that in fact the data does *not* give a single clear result (the point estimate) but a whole range of possibilities.

How is a confidence interval built, and how should it be interpreted? It does *not* mean that 95% of the data lies in that interval - instead, the frequentist interpretation is "if we were to repeat this experiment 100 times, we would expect the average result to lie in this interval ~95 times."

For a 95% confidence interval and a normal(-ish) distribution, you can simply remember that +/-2 standard deviations contains 95% of the probability mass, and so the 95% confidence interval based on a given sample is centered at the mean (point estimate) and has a range of +/- 2 (or technically 1.96) standard deviations.

Different distributions/assumptions (90% confidence, 99% confidence) will require different math, but the overall process and interpretation (with a frequentist approach) will be the same.

Your assignment - using the data from the prior module ([congressional voting records](https://archive.ics.uci.edu/ml/datasets/Congressional+Voting+Records)):


### Confidence Intervals:
1. Generate and numerically represent a confidence interval
2. Graphically (with a plot) represent the confidence interval
3. Interpret the confidence interval - what does it tell you about the data and its distribution?

### Chi-squared tests:
4. Take a dataset that we have used in the past in class that has **categorical** variables. Pick two of those categorical variables and run a chi-squared tests on that data
  - By hand using Numpy
  - In a single line using Scipy

In [0]:
# imports
from scipy.stats import ttest_ind, ttest_ind_from_stats, ttest_rel, ttest_1samp
import numpy as np
import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# getting the dataset
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/voting-records/house-votes-84.data

--2019-09-17 22:13:02--  https://archive.ics.uci.edu/ml/machine-learning-databases/voting-records/house-votes-84.data
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 18171 (18K) [application/x-httpd-php]
Saving to: ‘house-votes-84.data’

house-votes-84.data 100%[===================>]  17.75K  --.-KB/s    in 0.1s

2019-09-17 22:13:03 (127 KB/s) - ‘house-votes-84.data’ saved [18171/18171]

In [2]:
# gotta load that data too
df = pd.read_csv('house-votes-84.data',
                 header=None,
                 names=['party', 'handicapped-infants', 'water-project',
                       'budget', 'physician-fee-freeze', 'el-salvador-aid',
                       'religious-groups', 'anti-satellite-ban',
                       'aid-to-contras', 'mx-missile', 'immigration',
                       'synfuels', 'education', 'right-to-sue', 'crime',
                       'duty-free', 'south-africa'])

print(df.shape)
df.head()

(435, 17)

        party handicapped-infants water-project  ... crime duty-free south-africa
0  republican                   n             y  ...     y         n            y
1  republican                   n             y  ...     y         n            ?
2    democrat                   ?             y  ...     y         n            n
3    democrat                   n             y  ...     n         n            y
4    democrat                   y             y  ...     y         y            y

[5 rows x 17 columns]

In [0]:
# replace all values with 0's or 1's, unless they are '?', then they are a NaN
df = df.replace({'?':np.NaN, 'n':0, 'y':1})

In [4]:
dem = df[df['party'] == 'democrat']
dem.head()

      party  handicapped-infants  water-project  ...  crime  duty-free  south-africa
2  democrat                  NaN            1.0  ...    1.0        0.0           0.0
3  democrat                  0.0            1.0  ...    0.0        0.0           1.0
4  democrat                  1.0            1.0  ...    1.0        1.0           1.0
5  democrat                  0.0            1.0  ...    1.0        1.0           1.0
6  democrat                  0.0            1.0  ...    1.0        1.0           1.0

[5 rows x 17 columns]

In [0]:
# Confidence interval with regular non dataframe data, Numpy array
def confidence_interval(data, confidence=0.5):
  """
  Calculate a confidence interval around a sample mean for given data.
  Using t-distrivution and two-tailed test, default 95% confidence.
  
  Arguments:
    data - iterable (list or numpy array) of sample observations
    confidence - level of confidence for the interval
    
  Returns:
    tuple of (mean, lower bound, upper bound)
  """
  data = np.array(data)
  mean = np.mean(data)
  n = len(data)
  stderr = np.std(data, ddof=1) / np.sqrt(n)
  margin_of_error = stderr * stats.t.ppf((1 - confidence) / 2, n - 1)
  return (mean, mean - margin_of_error, mean + margin_of_error)

In [0]:
# Confidence interval for dataframes
def confidence_interval_dataframe(df):
  confidence_intervals = []
  
  df = df.values.T
  
  cleaned_df = []
  for col in df:
    cleaned_col = col[~np.isnan(col)]
    
    confidence_intervals.append(confidence_interval(cleaned_col))
  
  confidence_intervals = pd.DataFrame(confidence_intervals, columns=['mean','lower','upper'])
  return confidence_intervals

In [23]:
rep_votes = dem.drop('party', axis='columns')

confidence_interval_rep = confidence_interval_dataframe(rep_votes)
confidence_interval_rep.head(30)

        mean     lower     upper
0   0.604651  0.625251  0.584051
1   0.502092  0.523986  0.480198
2   0.888462  0.901674  0.875250
3   0.054054  0.063563  0.044545
4   0.215686  0.233118  0.198255
5   0.476744  0.497788  0.455700
6   0.772201  0.789838  0.754564
7   0.828897  0.844612  0.813183
8   0.758065  0.776471  0.739658
9   0.471483  0.492313  0.450653
10  0.505882  0.527072  0.484693
11  0.144578  0.159663  0.129494
12  0.289683  0.309023  0.270343
13  0.350195  0.370333  0.330056
14  0.637450  0.657988  0.616913
15  0.935135  0.947406  0.922864

## Stretch goals:

1. Write a summary of your findings, mixing prose and math/code/results. *Note* - yes, this is by definition a political topic. It is challenging but important to keep your writing voice *neutral* and stick to the facts of the data. Data science often involves considering controversial issues, so it's important to be sensitive about them (especially if you want to publish).
2. Apply the techniques you learned today to your project data or other data of your choice, and write/discuss your findings here.
3. Refactor your code so it is elegant, readable, and can be easily run for all issues.

## Resources

- [Interactive visualize the Chi-Squared test](https://homepage.divms.uiowa.edu/~mbognar/applets/chisq.html)
- [Calculation of Chi-Squared test statistic](https://en.wikipedia.org/wiki/Pearson%27s_chi-squared_test)
- [Visualization of a confidence interval generated by R code](https://commons.wikimedia.org/wiki/File:Confidence-interval.svg)
- [Expected value of a squared standard normal](https://math.stackexchange.com/questions/264061/expected-value-calculation-for-squared-normal-distribution) (it's 1 - which is why the expected value of a Chi-Squared with $n$ degrees of freedom is $n$, as it's the sum of $n$ squared standard normals)